ocfinance/urls.py
from django.urls import path
from . import views
from django.urls.conf import include
from django.contrib.auth import views as djangoViews

app_name = "ocfinance"

urlpatterns = [
    path("", views.Framework.as_view(), name="framework"),
    
    path("login/", views.Login.as_view(), name="login"),
    path("password/reset/", views.PasswordReset.as_view(), name="password_reset"),
    path("password/reset/sent/", views.PasswordResetSent.as_view(), name="password_reset_sent"),
    path("password/reset/confirm/<uidb64>/<token>/", views.PasswordResetConfirm.as_view(), name="password_reset_confirm"),
    path("password/reset/complete/", views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path("logout/", djangoViews.LogoutView.as_view(), name="logout"),
    path("password/change/", views.PasswordChange.as_view(), name="password_change"),
    path("password/change/done", views.PasswordChangeDone.as_view(), name="password_change_done"),
    
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("profile/", views.Profile.as_view(), name="profile"),
    
    path("contacts/", views.Contacts.as_view(), name="contacts"),
    path("contacts/all.json", views.AllContacts.as_view(), name="all_contacts"),
    path("contacts/staff.json", views.StaffData.as_view(), name="staff_data"),
    path("contacts/customers.json", views.CustomerData.as_view(), name="customer_data"),
    path("contacts/suppliers.json", views.SupplierData.as_view(), name="supplier_data"),
    path("contacts/new/", views.NewContact.as_view(), name="new_contact"),
]

# PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

opencrunch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('crunchcore.urls'), name='occ_root'),
    path('', include('ocfinance.urls'), name='ocf_root'),
]

crunchcore/models.py
# Part of OpenCrunch, see LICENSE.md and README.md
# https://gitlab.com/ocgroup1/opencrunch/
# (c) 2020 Dan Ladds AGPL v3

from django.db import models
from decimal import Decimal
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel
from django.utils import timezone
from django_countries.fields import CountryField
from django.conf import settings as djangoSettings

import pytz
import pycountry
import phonenumbers


class Entity(PolymorphicModel):
    """A person, business, organisation, informal group, etc.
    
    Roughly follows the v-card standard with a view to CARDDAV compat
    v-card parameter names are noted where applicable"""
    class Meta:
        verbose_name_plural = "entities"
    
    """Person or org name (FN)"""
    name = models.CharField(max_length=40, null=False, blank=False)
    
    """Photo or logo (PHOTO)"""
    photo = models.ImageField(upload_to="entity-photos", null=True, blank=True, default=None)
    
    """Street address (ADR-component-street)"""
    address = models.CharField(max_length=40, null=False, blank=True, default="")
    
    """Town or village (ADR-component-locality)"""
    locality = models.CharField(max_length=40, null=False, blank=True, default="")
    
    """Region (ADR-component-region)"""
    region = models.CharField(max_length=40, null=False, blank=True, default="")
    
    """Post or Zip code (ADR-component-code"""
    postcode = models.CharField(max_length=10, null=False, blank=True, default="")
    
    """Country or nation (ADR-component-country)"""
    country = CountryField()
    
    """Timezone"""
    timezone = models.CharField(max_length=32, choices=tuple(map(lambda x, y: [x, y], pytz.all_timezones, pytz.all_timezones)), blank=False, null=False)
    
    @property
    def localtime(self):
        return timezone.localtime(timezone=self.timezone)
    
    """Other entities with which this entity has a relationship"""
    relatedEntities = models.ManyToManyField('Entity', through='EntityRelation')
    
    """Login user (if this entity has one)"""
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.name

"""Language that an entity speaks

Field 'language' is an ID from/for pycountry"""
class EntityLanguage(PolymorphicModel):
    entity = models.ForeignKey(Entity, null=False, on_delete=models.CASCADE)
    language = models.CharField(max_length=7, choices=djangoSettings.LANGUAGES, null=False, blank=False)

"""Telephone number"""
class PhoneNumber(PolymorphicModel):
    entity = models.ForeignKey(Entity, null=False, on_delete=models.CASCADE)
    countryCode = models.CharField(max_length=3, blank=False, null=False)
    number = models.CharField(max_length=16, blank=False, null=False)
    sms = models.BooleanField(default=False)
    video = models.BooleanField(default=False)
    fax = models.BooleanField(default=False)
    cell = models.BooleanField(default=False)
    textphone = models.BooleanField(default=False)
    whatsapp = models.BooleanField(default=False)
    telegram = models.BooleanField(default=False)
    signal = models.BooleanField(default=False)

"""Email or instant messaging account"""
class MailMessageAddress(PolymorphicModel):
    entity = models.ForeignKey(Entity, null=False, on_delete=models.CASCADE)
    address = models.CharField(max_length=128, blank=False, null=False)
    email = models.BooleanField(default=False)
    facebook = models.BooleanField(default=False)
    twitter = models.BooleanField(default=False)
    instagram = models.BooleanField(default=False)
    linkedin = models.BooleanField(default=False)
    other = models.CharField(max_length=32, null=True, blank=True)

class EntityRelation(PolymorphicModel):
    """Relationship between two entities"""
    primaryEntity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='related_primary_set')    
    secondaryEntity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='related_secondary_set')
    relationship = models.CharField(max_length=255, blank=True)

class Account(PolymorphicModel):
    u"""A countable relationship between entities"""
    relation = models.ForeignKey(EntityRelation, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False)
    units = models.ForeignKey('UnitType', on_delete=models.PROTECT)
    preApprove = models.BooleanField(default=False)

class UnitType(PolymorphicModel):
    """A unit type, such as a currency"""
    name  = models.CharField(max_length=255)
    conversions = models.ManyToManyField('UnitType', through='UnitConversion')

class UnitConversion(PolymorphicModel):
    """Conversion between two unit types"""
    primaryUnit = models.ForeignKey(UnitType, on_delete=models.CASCADE, related_name='primary_conversion_set')
    secondaryUnit = models.ForeignKey(UnitType, on_delete=models.CASCADE, related_name='secondary_conversion_set')
    ratio = models.DecimalField(max_digits=30, decimal_places=2) 
    def reverse(self):
        out = UnitConversion()
        out.primaryUnit = self.secondaryUnit
        out.secondaryUnit = self.primaryUnit
        out.ratio = 1 / self.ratio
        return out

class Action(PolymorphicModel):
    """Modification to the value of an account"""
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=30, decimal_places=2)
    when = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

class Transaction(PolymorphicModel):
    """Pair of Actions representing transfer of units between accounts"""
    primaryAction = models.ForeignKey(Action, on_delete=models.PROTECT, related_name='primary_transaction_set')
    secondaryAction = models.ForeignKey(Action, on_delete=models.PROTECT, related_name='secondary_transaction_set')

ocfinance/models.py
# Part of OpenCrunch, see LICENSE.md and README.md
# https://gitlab.com/ocgroup1/opencrunch/
# (c) 2020 Dan Ladds AGPL v3

from django.db import models
from decimal import Decimal
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel
from django.utils import timezone
from crunchcore.models import Entity

"""Address book / accounts contact

Adds some extra fields to Entity"""
class Contact(Entity):
    pass
    

class Invoice(PolymorphicModel):
    pass
    

ocfinance/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, ButtonHolder, Submit
from django.contrib.auth import forms as djangoForms

class Login(djangoForms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(Login, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()     
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "username", 
                    css_class="form-control-user",
                    placeholder=self.fields["username"].label,
                ),
                Field(
                    "password", 
                    css_class="form-control-user",
                    placeholder=self.fields["password"].label,
                ),
                ButtonHolder(
                    Submit("submit", "Sign In", css_class="btn-user btn-block"),
                ),
            ), 
        )
        
        self.fields["username"].label = False
        self.fields["password"].label = False

class PasswordReset(djangoForms.PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordReset, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "email", 
                    css_class="form-control-user",
                    placeholder=self.fields["email"].label,
                ),
            ), 
        )
        
        self.fields["email"].label = False
        
class SetPassword(djangoForms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPassword, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "new_password1", 
                    css_class="form-control-user",
                    placeholder=self.fields["new_password1"].label,
                ),
                Field(
                    "new_password2", 
                    css_class="form-control-user",
                    placeholder=self.fields["new_password2"].label,
                ),
                ButtonHolder(
                    Submit("submit", "Change Password", css_class="btn-user btn-block"),
                ),
            ), 
        )
        
        self.fields["new_password1"].label = False
        self.fields["new_password2"].label = False
        

ocfinance/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import views as djangoViews
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models as djangoModels
from django_countries.fields import Country

from . import forms
from . import models

# Framework Features
class Framework(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/framework.html'))

# System Pages
class Dashboard(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/dashboard.html'))

class Profile(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/profile.html'))

class Settings(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/settings.html'))

# Authentication
class Login(djangoViews.LoginView):
    authentication_form = forms.Login
    template_name="user/login.html"
    
class PasswordReset(djangoViews.PasswordResetView):
    form_class = forms.PasswordReset
    template_name="user/password_reset.html"
    email_template_name = "user/password_reset_mail.html"
    success_url=reverse_lazy("ocfinance:password_reset_sent")
    
class PasswordResetSent(djangoViews.PasswordResetDoneView):
    template_name="user/password_reset_sent.html"
    
class PasswordResetConfirm(djangoViews.PasswordResetConfirmView):
    form_class = forms.SetPassword
    template_name="user/password_reset_confirm.html"
    success_url=reverse_lazy("ocfinance:password_reset_complete")

class PasswordResetComplete(djangoViews.PasswordResetCompleteView):
    template_name="user/password_reset_complete.html"

class PasswordChange(djangoViews.PasswordChangeView):
    template_name="user/password_change.html"

class PasswordChangeDone(djangoViews.PasswordChangeDoneView):
    template_name="user/password_change_done.html"

# JSON Handling
# TODO: Probably put this somewhere else i.e. in core
"""JSON encoder that knows how to handle extra fields

Handles ImageFieldFile, Country"""
class JsonEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, djangoModels.fields.files.ImageFieldFile):
            return o.name
        elif isinstance(o, Country):
            return o.name
        else:
            return super().default(o)

# Contacts
class Contacts(View):
    def get(self, request):
        return HttpResponse(render(request, "ocfinance/contacts_all.html"))
        
class AllContacts(View):
    def get(self, request):
        items = tuple(map(lambda x : model_to_dict(x), models.Entity.objects.all()))
        
    
        return JsonResponse(items, safe=False, encoder=JsonEncoder)

class StaffData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

class CustomerData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

class SupplierData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})
        
class NewContact(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

ocfinance/templates/ocfinance/contacts_all.html
{% load i18n %}{% load static %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{% trans 'All Contacts' %}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-delete fa-sm text-white-50"></i> Delete</a>
</div>

<div class="row align-items-start">
    <div class="col-sm">
        <table id="contact-table" class="display">
        </table>
    </div>
</div>
<script>
    $(function() {
        $('#contact-table').DataTable({
            'ajax' : {
                        'url' : '/contacts/all.json',
                        'dataSrc' : ''
            },
            'columns' : [
              { data : 'name', title : "Name"},
              { data : 'region', title : "City/County"},
              { data : 'country', title : "Country" }
            ]
        });
    });
</script>

ocfinance/templates/ocfinance/dashboard.html
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>

ocfinance/templates/ocfinance/framework.html
<!DOCTYPE html>{% load i18n %}{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
	<head>
		<title>{% trans "OpenCrunch Financial - Dashboard" %}</title>
		<!-- General -->
		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  		<meta name="description" content="">
  		<meta name="author" content="OpenCrunch">

		<!-- Bootstrap -->
		<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">

		<!-- Datatables -->
	  <link rel="stylesheet" href="{% static 'css/datatables/jquery.dataTables.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/datatables/dataTables.bootstrap4.css' %}" />

		<!-- Fontawesome -->
		<link rel="stylesheet" href="{% static 'css/fontawesome/all.css' %}" />

		<!-- Bootstrap theme - SB - https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 -->
		<link href="{% static 'css/sbadmin/sb-admin-2.css' %}" rel="stylesheet" type="text/css">

		<!-- OpenCrunch styles -->
		<link href="{% static 'css/oc.css' %}" rel="stylesheet" type="text/css" />

	</head>
	<body>

		<!-- Page Wrapper -->
		<div id="wrapper">

			{% include 'ocfinance/menu.html' %}

			<!-- Content Wrapper -->
			<div id="content-wrapper" class="d-flex flex-column">

			  <!-- Main Content -->
			  <div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

				  <!-- Sidebar Toggle (Topbar) -->
				  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
				    <i class="fa fa-bars"></i>
				  </button>

				  <!-- Topbar Search -->
				  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
				    <div class="input-group">
				      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
				      <div class="input-group-append">
				        <button class="btn btn-primary" type="button">
				          <i class="fas fa-search fa-sm"></i>
				        </button>
				      </div>
				    </div>
				  </form>

				  <!-- Topbar Navbar -->
				  <ul class="navbar-nav ml-auto">

				    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
				    <li class="nav-item dropdown no-arrow d-sm-none">
				      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				        <i class="fas fa-search fa-fw"></i>
				      </a>
				      <!-- Dropdown - Messages -->
				      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
				        <form class="form-inline mr-auto w-100 navbar-search">
				          <div class="input-group">
				            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
				            <div class="input-group-append">
				              <button class="btn btn-primary" type="button">
				                <i class="fas fa-search fa-sm"></i>
				              </button>
				            </div>
				          </div>
				        </form>
				      </div>
				    </li>

				    <!-- Nav Item - Alerts -->
				    <li class="nav-item dropdown no-arrow mx-1">
				      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				        <i class="fas fa-bell fa-fw"></i>
				        <!-- Counter - Alerts -->
				        <span class="badge badge-danger badge-counter">3+</span>
				      </a>
				      <!-- Dropdown - Alerts -->
				      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
				        <h6 class="dropdown-header">
				          Alerts Center
				        </h6>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="mr-3">
				            <div class="icon-circle bg-primary">
				              <i class="fas fa-file-alt text-white"></i>
				            </div>
				          </div>
				          <div>
				            <div class="small text-gray-500">December 12, 2019</div>
				            <span class="font-weight-bold">A new monthly report is ready to download!</span>
				          </div>
				        </a>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="mr-3">
				            <div class="icon-circle bg-success">
				              <i class="fas fa-donate text-white"></i>
				            </div>
				          </div>
				          <div>
				            <div class="small text-gray-500">December 7, 2019</div>
				            $290.29 has been deposited into your account!
				          </div>
				        </a>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="mr-3">
				            <div class="icon-circle bg-warning">
				              <i class="fas fa-exclamation-triangle text-white"></i>
				            </div>
				          </div>
				          <div>
				            <div class="small text-gray-500">December 2, 2019</div>
				            Spending Alert: We've noticed unusually high spending for your account.
				          </div>
				        </a>
				        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
				      </div>
				    </li>

				    <!-- Nav Item - Messages -->
				    <li class="nav-item dropdown no-arrow mx-1">
				      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				        <i class="fas fa-envelope fa-fw"></i>
				        <!-- Counter - Messages -->
				        <span class="badge badge-danger badge-counter">7</span>
				      </a>
				      <!-- Dropdown - Messages -->
				      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
				        <h6 class="dropdown-header">
				          Message Center
				        </h6>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="dropdown-list-image mr-3">
				            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
				            <div class="status-indicator bg-success"></div>
				          </div>
				          <div class="font-weight-bold">
				            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
				            <div class="small text-gray-500">Emily Fowler · 58m</div>
				          </div>
				        </a>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="dropdown-list-image mr-3">
				            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
				            <div class="status-indicator"></div>
				          </div>
				          <div>
				            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
				            <div class="small text-gray-500">Jae Chun · 1d</div>
				          </div>
				        </a>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="dropdown-list-image mr-3">
				            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
				            <div class="status-indicator bg-warning"></div>
				          </div>
				          <div>
				            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
				            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
				          </div>
				        </a>
				        <a class="dropdown-item d-flex align-items-center" href="#">
				          <div class="dropdown-list-image mr-3">
				            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
				            <div class="status-indicator bg-success"></div>
				          </div>
				          <div>
				            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
				            <div class="small text-gray-500">Chicken the Dog · 2w</div>
				          </div>
				        </a>
				        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
				      </div>
				    </li>

				    <div class="topbar-divider d-none d-sm-block"></div>

				    <!-- Nav Item - User Information -->
				    <li class="nav-item dropdown no-arrow">
				      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.entity.name }}</span>
				        <img class="img-profile rounded-circle" src="{% static 'img/' %}{{ request.user.entity.photo.url }}">
				      </a>
				      <!-- Dropdown - User Information -->
				      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
				        <a class="dropdown-item load-main" href="{% url 'ocfinance:profile' %}">
				          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
				          Profile
				        </a>
				        <a class="dropdown-item" href="#">
				          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
				          Preferences
				        </a>
				        <div class="dropdown-divider"></div>
				        <a class="dropdown-item" href="{% url 'ocfinance:logout' %}" data-toggle="modal" data-target="#logoutModal">
				          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
				          Logout
				        </a>
				      </div>
				    </li>

				  </ul>

				</nav>
				<!-- End of Topbar -->

				<!-- Begin Page Content -->
				<div class="container-fluid" id="page-pane">

				  

				</div>
				<!-- /.container-fluid -->

			  </div>
			  <!-- End of Main Content -->

			  <!-- Footer -->
			  <footer class="sticky-footer bg-white">
				<div class="container my-auto">
				  <div class="copyright text-center my-auto">
				    <span>Copyright &copy; OpenCrunch / Dan Ladds et al  2020</span>
				  </div>
				</div>
			  </footer>
			  <!-- End of Footer -->

			</div>
			<!-- End of Content Wrapper -->

		  </div>
		  <!-- End of Page Wrapper -->

		  <!-- Scroll to Top Button-->
		  <a class="scroll-to-top rounded" href="#page-top">
			<i class="fas fa-angle-up"></i>
		  </a>

		  <!-- Logout Modal-->
		  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
			  <div class="modal-content">
				<div class="modal-header">
				  <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
				  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
				    <span aria-hidden="true">×</span>
				  </button>
				</div>
				<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
				<div class="modal-footer">
				  <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
				  <a class="btn btn-primary" href="{% url 'ocfinance:logout' %}">Logout</a>
				</div>
			  </div>
			</div>
		  </div>

		<script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
  	<script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
  	<script src="{% static 'js/jquery-easing/jquery.easing.js' %}"></script>
  	<script src="{% static 'js/chart.js/Chart.js' %}"></script>
		<script src="{% static 'js/sbadmin/sb-admin-2.js' %}"></script>
		<script src="{% static 'js/datatables/jquery.dataTables.js' %}"></script>
		<script>src="{% static 'js/datatables/datatables.bootstrap4.js' %}"</script>
		<script src="{% static 'js/oc.js' %}"></script>

		

	</body>
</html>