ocfinance/urls.py
from django.urls import path
from . import views
from django.urls.conf import include
from django.contrib.auth import views as djangoViews

app_name = "ocfinance"

urlpatterns = [
    path("", views.Framework.as_view(), name="framework"),
    
    path("login/", views.Login.as_view(), name="login"),
    path("password/reset/", views.PasswordReset.as_view(), name="password_reset"),
    path("password/reset/sent/", views.PasswordResetSent.as_view(), name="password_reset_sent"),
    path("password/reset/confirm/<uidb64>/<token>/", views.PasswordResetConfirm.as_view(), name="password_reset_confirm"),
    path("password/reset/complete/", views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path("logout/", djangoViews.LogoutView.as_view(), name="logout"),
    path("password/change/", views.PasswordChange.as_view(), name="password_change"),
    path("password/change/done", views.PasswordChangeDone.as_view(), name="password_change_done"),
    
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("profile/", views.Profile.as_view(), name="profile"),
    
    path("contacts/", views.Contacts.as_view(), name="contacts"),
    path("contacts/all.json", views.AllContacts.as_view(), name="all_contacts"),
    path("contacts/staff.json", views.StaffData.as_view(), name="staff_data"),
    path("contacts/customers.json", views.CustomerData.as_view(), name="customer_data"),
    path("contacts/suppliers.json", views.SupplierData.as_view(), name="supplier_data"),
    path("contacts/new/", views.NewContact.as_view(), name="new_contact"),
]

# PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

opencrunch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('crunchcore.urls'), name='occ_root'),
    path('', include('ocfinance.urls'), name='ocf_root'),
]

ocfinance/models.py
# Part of OpenCrunch, see LICENSE.md and README.md
# https://gitlab.com/ocgroup1/opencrunch/
# (c) 2020 Dan Ladds AGPL v3

from django.db import models
from decimal import Decimal
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel
from django.utils import timezone
from crunchcore.models import Entity

"""Address book / accounts contact

Adds some extra fields to Entity"""
class Contact(Entity):
    pass
    

class Invoice(PolymorphicModel):
    pass
    

ocfinance/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, ButtonHolder, Submit
from django.contrib.auth import forms as djangoForms

class Login(djangoForms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(Login, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()     
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "username", 
                    css_class="form-control-user",
                    placeholder=self.fields["username"].label,
                ),
                Field(
                    "password", 
                    css_class="form-control-user",
                    placeholder=self.fields["password"].label,
                ),
                ButtonHolder(
                    Submit("submit", "Sign In", css_class="btn-user btn-block"),
                ),
            ), 
        )
        
        self.fields["username"].label = False
        self.fields["password"].label = False

class PasswordReset(djangoForms.PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordReset, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "email", 
                    css_class="form-control-user",
                    placeholder=self.fields["email"].label,
                ),
            ), 
        )
        
        self.fields["email"].label = False
        
class SetPassword(djangoForms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPassword, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                "",
                Field(
                    "new_password1", 
                    css_class="form-control-user",
                    placeholder=self.fields["new_password1"].label,
                ),
                Field(
                    "new_password2", 
                    css_class="form-control-user",
                    placeholder=self.fields["new_password2"].label,
                ),
                ButtonHolder(
                    Submit("submit", "Change Password", css_class="btn-user btn-block"),
                ),
            ), 
        )
        
        self.fields["new_password1"].label = False
        self.fields["new_password2"].label = False
        

ocfinance/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import views as djangoViews
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models as djangoModels
from django_countries.fields import Country

from . import forms
from . import models

# Framework Features
class Framework(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/framework.html'))

# System Pages
class Dashboard(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/dashboard.html'))

class Profile(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/profile.html'))

class Settings(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse(render(request, 'ocfinance/settings.html'))

# Authentication
class Login(djangoViews.LoginView):
    authentication_form = forms.Login
    template_name="user/login.html"
    
class PasswordReset(djangoViews.PasswordResetView):
    form_class = forms.PasswordReset
    template_name="user/password_reset.html"
    email_template_name = "user/password_reset_mail.html"
    success_url=reverse_lazy("ocfinance:password_reset_sent")
    
class PasswordResetSent(djangoViews.PasswordResetDoneView):
    template_name="user/password_reset_sent.html"
    
class PasswordResetConfirm(djangoViews.PasswordResetConfirmView):
    form_class = forms.SetPassword
    template_name="user/password_reset_confirm.html"
    success_url=reverse_lazy("ocfinance:password_reset_complete")

class PasswordResetComplete(djangoViews.PasswordResetCompleteView):
    template_name="user/password_reset_complete.html"

class PasswordChange(djangoViews.PasswordChangeView):
    template_name="user/password_change.html"

class PasswordChangeDone(djangoViews.PasswordChangeDoneView):
    template_name="user/password_change_done.html"

# JSON Handling
# TODO: Probably put this somewhere else i.e. in core
"""JSON encoder that knows how to handle extra fields

Handles ImageFieldFile, Country"""
class JsonEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, djangoModels.fields.files.ImageFieldFile):
            return o.name
        elif isinstance(o, Country):
            return o.name
        else:
            return super().default(o)

# Contacts
class Contacts(View):
    def get(self, request):
        return HttpResponse(render(request, "ocfinance/contacts_all.html"))
        
class AllContacts(View):
    def get(self, request):
        items = tuple(map(lambda x : model_to_dict(x), models.Entity.objects.all()))
        
    
        return JsonResponse(items, safe=False, encoder=JsonEncoder)

class StaffData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

class CustomerData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

class SupplierData(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})
        
class NewContact(View):
    def get(self, request):
        return JsonResponse({'foo' : 'bar',})

ocfinance/templates/user/login.html
<!DOCTYPE html>{% load i18n %}{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        {% load crispy_forms_tags %}
        <title>{% trans "OpenCrunch Financial - Login" %}</title>
        <!-- General -->
        <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <meta name="description" content="">
          <meta name="author" content="OpenCrunch">

        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">

        <!-- Datatables -->
        <link rel="stylesheet" href="{% static 'css/datatables/dataTables.bootstrap4.css' %}" />

        <!-- Fontawesome -->
        <link rel="stylesheet" href="{% static 'css/fontawesome/all.css' %}" />

        <!-- Bootstrap theme - SB - https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 -->
        <link href="{% static 'css/sbadmin/sb-admin-2.css' %}" rel="stylesheet" type="text/css">

        <!-- OpenCrunch styles -->
        <link href="{% static 'css/oc.css' %}" rel="stylesheet" type="text/css" />

    </head>
    <body class="bg-gradient-primary">
    
        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

              <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                  <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                      <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                      <div class="col-lg-6">
                        <div class="p-5">
                          <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                          </div>
                          <!--<form class="user" method="post" action="{% url 'ocfinance:login' %}">-->
                            {% csrf_token %}
                            {% crispy form %}
                            <!--<div class="form-group">
                              <div class="custom-control custom-checkbox small">
                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                <label class="custom-control-label" for="customCheck">Remember Me</label>
                              </div>
                            </div>-->
                          <hr>
                          <div class="text-center">
                            <a class="small load-modal-reset" href="{% url 'ocfinance:password_reset' %}">Forgot Password?</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>

        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="pwResetModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Reset Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Reset Password</button>
              </div>
            </div>
          </div>
        </div>
    
        <script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/jquery-easing/jquery.easing.js' %}"></script>
        <script src="{% static 'js/chart.js/Chart.js' %}"></script>
        <script src="{% static 'js/sbadmin/sb-admin-2.js' %}"></script>
        <script src="{% static 'js/oc.js' %}"></script>
        

    </body>
</html>

ocfinance/templates/user/password_reset.html
{% load i18n %}{% load static %}
{% load crispy_forms_tags %}
{% crispy form %}
      

ocfinance/templates/user/password_reset_complete.html
<!DOCTYPE html>{% load i18n %}{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        {% load crispy_forms_tags %}
        <title>{% trans "OpenCrunch Financial - Password Reset" %}</title>
        <!-- General -->
        <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <meta name="description" content="">
          <meta name="author" content="OpenCrunch">

        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">

        <!-- Datatables -->
        <link rel="stylesheet" href="{% static 'css/datatables/dataTables.bootstrap4.css' %}" />

        <!-- Fontawesome -->
        <link rel="stylesheet" href="{% static 'css/fontawesome/all.css' %}" />

        <!-- Bootstrap theme - SB - https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 -->
        <link href="{% static 'css/sbadmin/sb-admin-2.css' %}" rel="stylesheet" type="text/css">

        <!-- OpenCrunch styles -->
        <link href="{% static 'css/oc.css' %}" rel="stylesheet" type="text/css" />

    </head>
    <body class="bg-gradient-primary">
    
        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

              <div class="col-xl-8 col-lg-8 col-md-6">

                <div class="card o-hidden border-0 shadow-lg my-5">
                  <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row justify-content-center">
                      <div class="col-lg-16">
                        <div class="p-5">
                          <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">{% trans 'Done' %}</h1>
                          </div>
                            <p class="text-center">Password Reset Complete</p>
                            <p class="text-center"><a href="{% url 'ocfinance:framework' %}">Sign in</a></p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>

          </div>

    
        <script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/jquery-easing/jquery.easing.js' %}"></script>
        <script src="{% static 'js/chart.js/Chart.js' %}"></script>
        <script src="{% static 'js/sbadmin/sb-admin-2.js' %}"></script>

        

    </body>
</html>

ocfinance/templates/user/password_reset_confirm.html
<!DOCTYPE html>{% load i18n %}{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        {% load crispy_forms_tags %}
        <title>{% trans "OpenCrunch Financial - Password Reset" %}</title>
        <!-- General -->
        <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
          <meta name="description" content="">
          <meta name="author" content="OpenCrunch">

        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">

        <!-- Datatables -->
        <link rel="stylesheet" href="{% static 'css/datatables/dataTables.bootstrap4.css' %}" />

        <!-- Fontawesome -->
        <link rel="stylesheet" href="{% static 'css/fontawesome/all.css' %}" />

        <!-- Bootstrap theme - SB - https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 -->
        <link href="{% static 'css/sbadmin/sb-admin-2.css' %}" rel="stylesheet" type="text/css">

        <!-- OpenCrunch styles -->
        <link href="{% static 'css/oc.css' %}" rel="stylesheet" type="text/css" />

    </head>
    <body class="bg-gradient-primary">
    
        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

              <div class="col-xl-8 col-lg-8 col-md-6">

                <div class="card o-hidden border-0 shadow-lg my-5">
                  <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row justify-content-center">
                      <div class="col-lg-16">
                        <div class="p-5">
                          <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">{% trans 'Reset Password' %}</h1>
                            {% if form.errors %}
                            <div class="card bg-danger text-white shadow">
                                <div class="card-body">
                                  Danger
                                  <div class="text-white-50 small">#e74a3b</div>
                                </div>
                              </div>
                              <hr />
                            {% endif %}
                          </div>
                            {% csrf_token %}
                            {% crispy form %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>

          </div>

    
        <script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'js/bootstrap/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/jquery-easing/jquery.easing.js' %}"></script>
        <script src="{% static 'js/chart.js/Chart.js' %}"></script>
        <script src="{% static 'js/sbadmin/sb-admin-2.js' %}"></script>

        

    </body>
</html>

ocfinance/templates/user/password_reset_mail.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'ocfinance:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
	
{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}

ocfinance/templates/user/password_reset_sent.html
{% load i18n %}{% load static %}

Please check your email to reset your password.

<script>$('#pwResetModal .btn-primary').hide();</script>